//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang ebpf bpf/syscall.c

//go:build ebpf
// +build ebpf

package tracer

import (
	"context"
	"fmt"
	"os/exec"
	"reflect"
	"syscall"
	"time"
	"unsafe"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"

	"github.com/fabianoflorentino/stracectl/internal/models"
)

// ebpfEvent must exactly mirror the C struct above
type ebpfEvent struct {
	PID       uint32
	SyscallNr uint32
	Ret       int64
	EnterNs   uint64
	ExitNs    uint64
	Args      [6]uint64
}

// EBPFTracer traces syscalls via eBPF without a subprocess.
type EBPFTracer struct{}

func NewEBPFTracer() *EBPFTracer { return &EBPFTracer{} }

func (t *EBPFTracer) Attach(ctx context.Context, pid int) (<-chan models.SyscallEvent, error) {
	return t.trace(ctx, pid)
}

func (t *EBPFTracer) Run(ctx context.Context, program string, args []string) (<-chan models.SyscallEvent, error) {
	// Start the traced program and attach the eBPF tracer to its PID.
	// Mirror the process-group handling used by the Strace tracer so the
	// entire traced process group is killed on cancellation.
	cmd := exec.CommandContext(ctx, program, args...)

	cmd.SysProcAttr = &syscall.SysProcAttr{}
	if setpgid := reflect.ValueOf(cmd.SysProcAttr).Elem().FieldByName("Setpgid"); setpgid.IsValid() && setpgid.CanSet() && setpgid.Kind() == reflect.Bool {
		setpgid.SetBool(true)
	}

	// Override Cancel to kill the process group when available.
	cmd.Cancel = func() error {
		if cmd.Process == nil {
			return nil
		}

		killPID := cmd.Process.Pid
		if cmd.SysProcAttr != nil {
			if setpgid := reflect.ValueOf(cmd.SysProcAttr).Elem().FieldByName("Setpgid"); setpgid.IsValid() && setpgid.Kind() == reflect.Bool && setpgid.Bool() {
				killPID = -killPID
			}
		}

		_ = syscall.Kill(killPID, syscall.SIGKILL)
		return nil
	}

	if err := cmd.Start(); err != nil {
		return nil, fmt.Errorf("start traced process: %w", err)
	}

	pid := cmd.Process.Pid

	// tracerCtx is cancelled when the traced process exits or the parent ctx
	// is cancelled. When tracerCtx is cancelled the eBPF trace goroutine will
	// exit (see t.trace which listens on the context).
	tracerCtx, cancel := context.WithCancel(ctx)

	go func() {
		// When the traced process exits, cancel the tracer context to stop
		// the eBPF reader goroutine.
		_ = cmd.Wait()
		cancel()
	}()

	events, err := t.trace(tracerCtx, pid)
	if err != nil {
		// If attaching/tracing failed, ensure the traced process is killed.
		_ = cmd.Cancel()
		return nil, err
	}

	return events, nil
}

func (t *EBPFTracer) trace(ctx context.Context, filterPID int) (<-chan models.SyscallEvent, error) {
	// Load BPF objects generated by bpf2go
	objs := ebpfObjects{}
	if err := loadEbpfObjects(&objs, nil); err != nil {
		return nil, fmt.Errorf("load bpf objects: %w", err)
	}

	// Attach to global raw tracepoints
	enterLink, err := link.AttachRawTracepoint(link.RawTracepointOptions{
		Name:    "sys_enter",
		Program: objs.SysEnter,
	})
	if err != nil {
		objs.Close()
		return nil, fmt.Errorf("attach sys_enter: %w", err)
	}

	exitLink, err := link.AttachRawTracepoint(link.RawTracepointOptions{
		Name:    "sys_exit",
		Program: objs.SysExit,
	})
	if err != nil {
		enterLink.Close()
		objs.Close()
		return nil, fmt.Errorf("attach sys_exit: %w", err)
	}

	rd, err := ringbuf.NewReader(objs.Events)
	if err != nil {
		enterLink.Close()
		exitLink.Close()
		objs.Close()
		return nil, fmt.Errorf("ringbuf reader: %w", err)
	}

	ch := make(chan models.SyscallEvent, 4096)

	go func() {
		defer close(ch)
		defer enterLink.Close()
		defer exitLink.Close()
		defer rd.Close()
		defer objs.Close()

		// Mapping from syscall number to name (generated from kernel headers)
		syscallNames := buildSyscallTable()

		for {
			select {
			case <-ctx.Done():
				return
			default:
			}

			record, err := rd.Read()
			if err != nil {
				return
			}

			var raw ebpfEvent
			copy(unsafe.Slice((*byte)(unsafe.Pointer(&raw)), unsafe.Sizeof(raw)),
				record.RawSample)

			// Filtra por PID se necessário
			if filterPID > 0 && int(raw.PID) != filterPID {
				continue
			}

			name := syscallNames[raw.SyscallNr]
			if name == "" {
				name = fmt.Sprintf("syscall_%d", raw.SyscallNr)
			}

			latency := time.Duration(raw.ExitNs - raw.EnterNs)

			ch <- models.SyscallEvent{
				PID:     int(raw.PID),
				Name:    name,
				RetVal:  fmt.Sprintf("%d", raw.Ret),
				Latency: latency,
				Time:    time.Now(),
			}
		}
	}()

	return ch, nil
}
