package tracer

import "testing"

// TestLoadEbpfSpec verifies that the embedded eBPF ELF blob parses into a
// CollectionSpec. This ensures the generated artifacts are present and valid.
// If no embedded bytes are present (e.g. CI runner did not generate BPF
// artifacts), the test is skipped instead of failing to avoid spurious
// failures in non-eBPF runners.
func TestLoadEbpfSpec(t *testing.T) {
	// _EbpfBytes is generated by bpf2go via go:embed; when the .o is missing
	// the slice may be empty. Skip the test in that case.
	if len(_EbpfBytes) == 0 {
		t.Skip("no embedded eBPF bytes; skipping")
	}

	spec, err := loadEbpf()
	if err != nil {
		t.Fatalf("loadEbpf returned error: %v", err)
	}
	if spec == nil {
		t.Fatalf("loadEbpf returned nil spec")
	}
}
