package ui

// syscallDesc maps common syscall names to a single-line beginner-friendly description.
var syscallDesc = map[string]string{
	// I/O
	"read":            "read data from a file or socket",
	"write":           "write data to a file or socket",
	"pread64":         "read from a file at a specific offset",
	"pwrite64":        "write to a file at a specific offset",
	"readv":           "read into multiple buffers at once",
	"writev":          "write from multiple buffers at once",
	"open":            "open a file",
	"openat":          "open a file (relative to a directory)",
	"close":           "close an open file descriptor",
	"dup":             "duplicate a file descriptor",
	"dup2":            "duplicate a file descriptor to a specific number",
	"dup3":            "duplicate a file descriptor with flags",
	"pipe":            "create a pipe for inter-process communication",
	"pipe2":           "create a pipe with flags",
	"sendfile":        "copy data between file descriptors in kernel",
	"copy_file_range": "copy data between files without userspace buffer",

	// FS
	"stat":              "get file metadata (size, permissions, etc.)",
	"fstat":             "get metadata of an open file",
	"lstat":             "get metadata of a symlink (not its target)",
	"newfstatat":        "get file metadata relative to a directory",
	"statx":             "get extended file metadata",
	"access":            "check if the process can access a file",
	"faccessat":         "check file access relative to a directory",
	"getdents":          "read directory entries",
	"getdents64":        "read directory entries (64-bit)",
	"mkdir":             "create a directory",
	"mkdirat":           "create a directory relative to another",
	"rmdir":             "remove an empty directory",
	"unlink":            "delete a file",
	"unlinkat":          "delete a file relative to a directory",
	"rename":            "rename or move a file",
	"renameat":          "rename a file relative to directories",
	"link":              "create a hard link",
	"symlink":           "create a symbolic link",
	"readlink":          "read the target of a symbolic link",
	"chmod":             "change file permissions",
	"chown":             "change file owner",
	"truncate":          "shrink or extend a file to a given size",
	"ftruncate":         "shrink or extend an open file",
	"lseek":             "move the read/write position in a file",
	"llseek":            "move position in a large file",
	"chdir":             "change current working directory",
	"fchdir":            "change current directory using a file descriptor",
	"getcwd":            "get the current working directory path",
	"statfs":            "get filesystem statistics (disk space, etc.)",
	"fstatfs":           "get filesystem stats for an open file's fs",
	"mount":             "attach a filesystem",
	"umount2":           "detach a filesystem",
	"sync":              "flush all pending disk writes",
	"fsync":             "flush a specific file's writes to disk",
	"fdatasync":         "flush file data (not metadata) to disk",
	"inotify_init":      "set up file-change notifications",
	"inotify_add_watch": "watch a file or directory for changes",

	// NET
	"socket":        "create a network socket",
	"bind":          "assign an address to a socket",
	"listen":        "mark a socket as ready to accept connections",
	"accept":        "accept an incoming connection",
	"accept4":       "accept an incoming connection with flags",
	"connect":       "connect a socket to a remote address",
	"sendto":        "send data over a socket",
	"recvfrom":      "receive data from a socket",
	"sendmsg":       "send a message with control data",
	"recvmsg":       "receive a message with control data",
	"sendmmsg":      "send multiple messages at once",
	"recvmmsg":      "receive multiple messages at once",
	"getsockname":   "get the local address of a socket",
	"getpeername":   "get the remote address of a socket",
	"setsockopt":    "configure socket options (timeouts, buffers…)",
	"getsockopt":    "read current socket options",
	"shutdown":      "close one or both sides of a socket",
	"socketpair":    "create a pair of connected sockets",
	"poll":          "wait for events on multiple file descriptors",
	"ppoll":         "wait for events, with timeout and signal mask",
	"select":        "wait for file descriptors to become ready",
	"epoll_create":  "create an epoll event set",
	"epoll_create1": "create an epoll event set with flags",
	"epoll_ctl":     "add/modify/remove a file descriptor in epoll set",
	"epoll_wait":    "wait for events in an epoll set",
	"epoll_pwait":   "wait for epoll events with signal mask",

	// MEM
	"mmap":     "map a file or memory into the process address space",
	"munmap":   "unmap previously mapped memory",
	"mprotect": "change memory region permissions (read/write/exec)",
	"madvise":  "give kernel hints about memory usage",
	"mremap":   "resize or move a memory mapping",
	"msync":    "flush memory-mapped file changes to disk",
	"brk":      "grow or shrink the heap",
	"mlock":    "prevent memory from being swapped out",
	"munlock":  "allow memory to be swapped again",
	"mlockall": "lock all process memory in RAM",

	// PROC
	"clone":           "create a new thread or process",
	"clone3":          "create a new thread/process (newer API)",
	"fork":            "create a child process (copy of parent)",
	"vfork":           "create a child process sharing parent memory",
	"execve":          "replace current process with a new program",
	"execveat":        "execute a program relative to a directory",
	"wait4":           "wait for a child process to finish",
	"waitpid":         "wait for a specific child process",
	"exit":            "terminate the current thread",
	"exit_group":      "terminate all threads in the process",
	"getpid":          "get the current process ID",
	"getppid":         "get the parent process ID",
	"getuid":          "get the user ID of the process",
	"geteuid":         "get the effective user ID",
	"getgid":          "get the group ID",
	"getegid":         "get the effective group ID",
	"prctl":           "control process settings (name, capabilities…)",
	"prlimit64":       "get or set resource limits (CPU, memory, files…)",
	"ptrace":          "inspect or control another process (used by debuggers)",
	"kill":            "send a signal to a process",
	"tgkill":          "send a signal to a specific thread",
	"arch_prctl":      "set architecture-specific thread state",
	"set_tid_address": "store thread ID pointer (used by the C library)",
	"set_robust_list": "register a list of robust mutexes (libc startup)",
	"rseq":            "register restartable sequence (performance optimisation)",
	"gettid":          "get the current thread ID",
	"getpgid":         "get the process group ID",
	"setsid":          "create a new session",
	"uname":           "get system information (kernel version, hostname…)",
	"gettimeofday":    "get current time",
	"clock_gettime":   "get time from a specific clock",
	"nanosleep":       "sleep for a precise duration",
	"futex":           "fast user-space mutex/semaphore (used by pthreads)",
	"getrandom":       "get random bytes from the kernel",
	"ioctl":           "device/terminal control (resize, flags, etc.)",
	"fcntl":           "control file descriptor flags (non-blocking, locks…)",
	"eventfd":         "create a file descriptor for event notifications",
	"eventfd2":        "create an event file descriptor with flags",

	// SIG
	"rt_sigaction":    "register a signal handler",
	"rt_sigprocmask":  "block or unblock signals",
	"rt_sigreturn":    "return from a signal handler",
	"rt_sigsuspend":   "wait for a signal",
	"rt_sigpending":   "check which signals are pending",
	"rt_sigtimedwait": "wait for a signal with a timeout",
	"signalfd":        "receive signals via a file descriptor",
	"signalfd4":       "receive signals via fd with flags",
}

// errDesc maps POSIX errno names to plain-language explanations.
var errDesc = map[string]string{
	"ENOENT":       "file or directory not found",
	"EACCES":       "permission denied",
	"EPERM":        "operation not permitted (need root or capability)",
	"EAGAIN":       "resource temporarily unavailable (try again) — normal for non-blocking I/O",
	"EWOULDBLOCK":  "would block on non-blocking socket — normal for async I/O",
	"EINTR":        "interrupted by a signal — the call will be retried",
	"ECONNREFUSED": "remote host refused the connection",
	"ETIMEDOUT":    "connection or operation timed out",
	"ENETUNREACH":  "no route to host (network unreachable)",
	"EADDRINUSE":   "address/port already in use",
	"EBADF":        "bad file descriptor (already closed or invalid)",
	"EINVAL":       "invalid argument passed to syscall",
	"ENOMEM":       "out of memory",
	"ENOSPC":       "no space left on device",
	"EMFILE":       "too many open files in this process",
	"ENFILE":       "too many open files system-wide",
	"EEXIST":       "file already exists",
	"ENOTDIR":      "expected a directory, got a file",
	"EISDIR":       "expected a file, got a directory",
	"ENOTEMPTY":    "directory is not empty",
	"ELOOP":        "too many symbolic links (possible loop)",
	"ENAMETOOLONG": "file name is too long",
	"ENOSYS":       "syscall not implemented on this kernel",
	"ENOTTY":       "not a TTY — ioctl called on a non-terminal fd",
	"ENXIO":        "no such device or address",
	"ERANGE":       "result out of range",
	"EDEADLK":      "resource deadlock would occur",
	"EPROTO":       "protocol error",
	"EPROTOBUF":    "protocol wrong type for socket",
	"EAFNOSUPPORT": "address family not supported (e.g. IPv6 not available)",
	"ECONNRESET":   "connection reset by peer",
	"EPIPE":        "broken pipe — writing to a closed reader",
	"ENOPROTOOPT":  "protocol option not available",
	"EOPNOTSUPP":   "operation not supported on this socket type",
	"ENOBUFS":      "no buffer space available",
	"ENOTCONN":     "socket is not connected",
	"EALREADY":     "connection already in progress",
	"EINPROGRESS":  "connection is being established (non-blocking connect)",
}

// syscallHint returns a short description for display. Falls back to empty string.
func syscallHint(name string) string {
	return syscallDesc[name]
}

// errHint returns a plain-language explanation for an errno name.
func errHint(errno string) string {
	return errDesc[errno]
}
